Script started on Fri 29 May 2015 09:56:51 PM PDT
~
phung001@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * checksyscalls.sh      is your cpp file doing proper error checking?     |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mphung001[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m CS100/rshell
bash: CS100/rshell: is a directory
[s%%%%%%%%%%[u[0;32mphung001[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd CS100/rshell/
[s%%%%%%%%%%[u[0;32mphung001[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m make
make: Nothing to be done for `all'.
[s%%%%%%%%%%[u[0;32mphung001[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m bin/rshell
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ cat #^c C tests
ls
ls
asd
asd
^C
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ^C
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ^C
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ^C
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ca  cd src #test    regular cd
phung001@hammer.cs.ucr.edu:~/CS100/rshell/src $ ls
cp.cpp	handle_signals.cpp  ls.cpp  mv.cpp  rm.cpp  terminal.cpp  timer.h
phung001@hammer.cs.ucr.edu:~/CS100/rshell/src $ cd - #cd with h a -
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ cd #test to go home
phung001@hammer.cs.ucr.edu:~ $ cd -
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ cd -
phung001@hammer.cs.ucr.edu:~ $ cd CS100/rshell/src #test with multiple directories
phung001@hammer.cs.ucr.edu:~/CS100/rshell/src $ cd ..
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ cd .
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ cd src/../src/../.
phung001@hammer.cs.ucr.edu:~/CS100/rshell $ exit
[s%%%%%%%%%%[u[0;32mphung001[0;36m@[0;32mcs100[0;36m:[0;32m~/CS100/rshell[0;95m (master) [0;36m$[0m exit
exit
~
phung001@hammer $ exit
exit

Script done on Fri 29 May 2015 10:01:41 PM PDT
